name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-cov pytest

      - name: Run tests
        run: pytest --cov=monitoring_system test_monitoring.py

      - name: Build Docker image
        run: docker compose -f monitoring-stack/docker-compose.yml build