name: Build and Publish Docker Image

on:
    push:
        branches:
            - main

permissions:
    contents: read
    packages: write

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Create test env file
              run: |
                echo "SLACK_WEBHOOK_URL=https://example.com/test" > .env
                echo "AWS_BUCKET_NAME=test-bucket" >> .env
                echo "AWS_REGION=eu-central-1" >> .env

            - name: Log in to Github Container Registry
              run: |
                echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Build Docker image
              run: |
                docker build -t ghcr.io/nexeruno/python-web-monitoring:latest .

            - name: Push Docker image
              run: |
                docker push ghcr.io/nexeruno/python-web-monitoring:latest    
                

